- name: test play
  hosts: all
  #hosts: el6host
  user: vagrant
  connection: ssh
  gather_facts: True
  max_fail_percentage: .1
  #serial: 1
  tasks:

    - name: show the hostname [local]
      shell: echo "{{ inventory_hostname }}"
      delegate_to: localhost

    - name: check my identity
      shell: uname -a

    - name: remove foobar
      shell: rm -rf /tmp/foobar*
      delegate_to: localhost

    - name: create foobar
      shell: echo "foobar" > /tmp/foobar 

    - name: create a local foobar
      copy:
          content: "foobar"
          dest: /tmp/foobar.txt
      delegate_to: localhost

    - name: fetch /tmp/foobar
      fetch:
        src: /tmp/foobar
        dest: /tmp/foobar

    - name: fetch /tmp/foobar [local]
      fetch:
        src: /tmp/foobar.txt
        dest: /tmp/foobar2
      delegate_to: localhost

    - name: remove sysstat
      yum:
        name: sysstat
        state: absent
      become: True

    - name: install sysstat
      yum:
        name: sysstat
        state: latest
      become: True

